and is &
Taiko2k/Tauon pull request #1187
Opened 2024-07-14 18:40 UTC by RSKYS

2024-07-15 00:18 UTC, Taiko2k commented
While this may fix some use cases I anticipate it may break others. Like what if what a user is searching actually includes the word "and". A more correct approach would be to perform a search comparison of both forms somehow but I would have performance reservations about that.

2024-07-15 06:51 UTC, RSKYS commented
My case is limited to these 5 variables in search anyway, but I might understand your point of view, it overwrites default search result of tracks with & too.
I'll think about it sometime later.

2024-07-30 21:38 UTC, Taiko2k requested changes

2024-07-30 21:38 UTC, Taiko2k commented on t_modules/t_main.py
> +                        if "and" in s_text:
This should go further up outside of the search loop

2024-07-30 21:38 UTC, Taiko2k commented on t_modules/t_main.py
> +                            search_string_cache.clear()
These need to be called when switching *and_mode*, so you will need another variable to keep track of the previous state and only clear the cache when the state changes. Again this can go outside of the search loop.

2024-07-30 21:38 UTC, Taiko2k commented on t_modules/t_main.py
> +                            if and_mode and "&" in title:
These can be placed in a single `if and_mode` block

2024-07-31 01:39 UTC, RSKYS commented on t_modules/t_main.py
> +                        if "and" in s_text:
Yea yea yea, I pushed these fast, was still thinking, you told me already, gonna come back.

2024-08-07 09:47 UTC, RSKYS commented
I'm not interested to write & thingy, it requires minor changes compared to what I did, but there's been few days I'm thinking if I should really contribute to the project or not anymore.
Do it yourself if you wanted, I stay out of  python.
Maybe maybe if I saw something worthy; right now I might sometimes contribute to phazor, there are some mpt things I'd put to practice later.

2024-08-07 09:47 UTC, closed without merging